### PR TITLE
fix: no default values on users

### PR DESCRIPTION
**Pull request by MrAnderson0309**

### CODE REVIEW

**Comment by MrAnderson0309** [comment]
@openam @mashu-daishi  let me know if you have an issue with this

**Review by openam — APPROVED** [review]
I'm fine with this. These are the only things that appear to have `default` values, which as we discovered screws things up when you want to do them as `.optional()`.

**Review by mashu-daishi — CHANGES_REQUESTED** [review]
You're going to need to increment the version number in the package.json file first.

**Comment by MrAnderson0309** [comment]
@mashu-daishi done

**Review by mashu-daishi — APPROVED** [review]

**Pull request merged**
